server:
  port: 8861

spring:
  application:
    name: cloud-config
  profiles: config-server1
  cloud:
    config:
      # 对应分支
      label: master
      server:
        git:
          # git地址
          uri: https://github.com/uywojh/springcloud_profile.git
          # 远程目录
          search-paths: cloud
          username: 664507439@qq.com
          password: wu15180180820

eureka:
  instance:
    hostname: 172.16.246.128        #Gateway实例的主机名
    prefer-ip-address: true
    instance-id: 172.16.246.128:8861
  client:
    serviceUrl:
      defaultZone: http://172.16.246.128:8761/eureka,http://172.16.246.128:8762/eureka